variables:
  NPM_REGISTRY_PUBLIC: "https://nexus.suilib.ru/repository/npm-public/" # Worldwide "https://registry.yarnpkg.com/"
  NPM_REGISTRY_SUI_REPO: "https://nexus.suilib.ru/repository/npm-sui/"
  NPM_REGISTRY_USER: "" # Set in variables
  NPM_REGISTRY_PASSWORD: "" # Set in variables

  MVN_REPOSITORY_CENTRAL: "https://nexus.suilib.ru/repository/mvn-central-proxy/" # Worldwide "https://repo1.maven.org/maven2/"
  MVN_REPOSITORY_CDH: "https://nexus.suilib.ru/repository/mvn-cdh-proxy/" # Worldwide "https://repository.cloudera.com/artifactory/cloudera-repos/"
  MVN_REPOSITORY_GRADLE_PLUGINS: "https://nexus.suilib.ru/repository/mvn-gradle-plugins-proxy/" # Worldwide "https://plugins.gradle.org/m2/"
  MVN_REPOSITORY_SUI: "https://nexus.suilib.ru/repository/mvn-sui/"
  MVN_REPOSITORY_USER: "" # Set in variables
  MVN_REPOSITORY_PASSWORD: "" # Set in variables

  BASEIMAGEREGISTRY: "nexus.suilib.ru/" # Worldwide ""

  BUILD_VERSION: "9.0.0-${CI_COMMIT_SHORT_SHA}"

stages:
  - build

java:
  image:
    name: ${BASEIMAGEREGISTRY}library/gradle:6.7-jdk8
    entrypoint: [""]
  stage: build
  tags:
    - sui-docker
  script:
    - cd java
    - gradle build --no-daemon
    - gradle publish --no-daemon

js:
  image:
    name: ${BASEIMAGEREGISTRY}library/node:16-alpine
    entrypoint: [""]
  stage: build
  tags:
    - sui-docker
  before_script:
    - echo "@sui:registry = ${NPM_REGISTRY_SUI_REPO}" > .npmrc
    - |
      NPM_REGISTRY="${NPM_REGISTRY_SUI_REPO}" \
      NPM_SCOPE="@sui/" \
      NPM_USER="${NPM_REGISTRY_USER}" \
      NPM_EMAIL="gitlab@ci.local" \
      NPM_PASS="${NPM_REGISTRY_PASSWORD}" \
      npx npm-cli-adduser
  script:
    - cd js
    - yarn install --frozen-lockfile
    - yarn bootstrap
    - yarn ci
    - yarn lcm publish ${BUILD_VERSION}
