version: '2.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    ports:
      - 4873:4873
    volumes:
       - verdaccio:/verdaccio
volumes:
  verdaccio:
    driver: local