///////////////////////////////////
//FILE IS AUTOGENERATED. DON'T EDIT
///////////////////////////////////
export const importsByNewPackage = {
  "@sui/lib-auth": [
    "AccessRights",
    "Allowed",
    "AuthorityList",
    "checkAuthority",
    "getPrivileges",
    "getUser",
    "hasAnyPrivilege",
    "hasPrivilege",
    "hasRole",
    "ICoreUser",
    "isAdmin",
    "LibAuthModule",
    "Privilege",
    "SYSTEM_USER_ID",
    "UserNotInitializedError",
    "UserService",
    "UserServiceImpl"
  ],
  "@sui/lib-cache-abstract": [
    "CacheEntryUpdatedEvent",
    "CacheManager",
    "ICacheEntry"
  ],
  "@sui/lib-color": [
    "Color",
    "ColorHeatMap",
    "findColorBetween",
    "IColorHeatMapSettings",
    "LibColorModule"
  ],
  "@sui/lib-event-manager": [
    "EventListenerDescriptor",
    "EventManager",
    "SuiEvent",
    "SuiEventListener"
  ],
  "@sui/lib-hooks": [
    "useAsyncEffect",
    "useAsyncState",
    "useHandler",
    "usePromise",
    "UsePromiseState",
    "useService",
    "useValue"
  ],
  "@sui/lib-module-manager": [
    "MainModule",
    "ModuleDepsInitEvent",
    "ModuleDepsInitializedEvent",
    "ModuleDiscoveredEvent",
    "ModuleDuplicateEvent",
    "ModuleErrorEvent",
    "ModuleEvent",
    "ModuleFailedEvent",
    "ModuleInitEvent",
    "ModuleInitializedEvent",
    "ModuleManager",
    "ModuleWithDurationEvent",
    "SuiModule"
  ],
  "@sui/lib-notification-dispatcher": [
    "ErrorEvent",
    "LibNotificationDispatcherModule",
    "NotificationArgsProps",
    "NotificationCloseEvent",
    "NotificationDispatcher",
    "NotificationDispatcherImpl",
    "NotificationEvent",
    "NotificationSeverity"
  ],
  "@sui/lib-storage": [
    "LocalStorageModule",
    "LocalStorageService",
    "LocalStorageServiceImpl",
    "LSKeyWrapper",
    "LSKeyWrapperImpl"
  ],
  "@sui/lib-typescript-ast": [
    "astQuery",
    "astRemove",
    "astReplace",
    "ImportWithAlias",
    "ParsedImportDeclaration",
    "parseImportDeclaration",
    "parseImportSpecifier",
    "printImportDeclaration",
    "printNode",
    "printNodes"
  ],
  "@sui/ui-actions": [
    "Button",
    "ButtonProps",
    "IOnClickIntegration",
    "IUsePopconfirmState",
    "PopconfirmSettings",
    "useOnClick",
    "UseOnClickState",
    "usePopconfirm"
  ],
  "@sui/ui-charts": [
    "CategoryColumnChart",
    "ChartWrapper",
    "ChordDiagramWrapper",
    "ForceDirectedTree",
    "ForceDirectedTreeWrapper",
    "IAdditionalSettingProps",
    "ICategoryColumnChartSeries",
    "IChartWrapperProps",
    "IForceDirectedTreeAdditionalSettingProps",
    "IForceDirectedTreeDataElement",
    "IReportTopBarChartSettingProps",
    "MapWrapper",
    "PieChart3DWrapper",
    "PieChartWrapper",
    "RadarChartWrapper",
    "ReportTopBarChart",
    "SlicedChartWrapper",
    "TreeMapWrapper",
    "WordCloudWrapper",
    "XYChart3DWrapper",
    "XYChartWrapper"
  ],
  "@sui/ui-idle-tracker": [
    "IdleTimerConsumer",
    "IdleTracker",
    "IIdleTimer",
    "UiIdleTrackerModule",
    "useIdleTimerContext"
  ],
  "@sui/ui-material": [
    "ProgressIcon",
    "ProgressIconProps",
    "TooltipWrapper",
    "TooltipWrapperProps"
  ],
  "@sui/ui-module-manager": [
    "ModuleManagerRoot"
  ],
  "@sui/ui-notification-handler": [
    "NotificationViewer",
    "UiNotificationHandlerModule"
  ],
  "@sui/ui-observable": [
    "IObservableBinderProps",
    "joinObservables2",
    "joinObservables3",
    "joinObservables4",
    "joinObservables5",
    "joinObservables6",
    "Observable",
    "ObservableBinder",
    "ObservableHandler",
    "ObservableHandlerStub",
    "ObservableLocalStorageValue"
  ],
  "@sui/ui-old-sentry": [
    "getSentry",
    "initSentry",
    "ISentry"
  ],
  "@sui/ui-themes": [
    "antdDefaultTheme",
    "AntdTheme",
    "compileFinalTheme",
    "getComponents",
    "ISuiThemeContext",
    "KludgeForStorybook",
    "mergeSuiComponentThemes",
    "muiDefaultTheme",
    "MuiTheme",
    "SuiComponentsTheme",
    "SuiComponentsThemeCompiled",
    "SuiComponentsThemeConfig",
    "SuiComponentTheme",
    "SuiComponentThemeCompiled",
    "SuiComponentThemeConfig",
    "suiDefaultTheme",
    "SuiTheme",
    "SuiThemeCompiled",
    "SuiThemeComponents",
    "SuiThemeConfig",
    "SuiThemeContext",
    "SuiThemeProvider",
    "SuiThemeVariants",
    "ThemeChangedEvent",
    "ThemeService",
    "ThemeServiceImpl",
    "ThemeSwitchButton",
    "UiThemesModule"
  ],
  "@sui/util-chore": [
    "addCss",
    "clamp",
    "concatDataKey",
    "DataKey",
    "DataKeyNode",
    "dataKeysToDataTree",
    "getDataByKey",
    "getTOrCall",
    "lazyInit",
    "normalizeDataKey",
    "sleep",
    "TOrCallback"
  ],
  "@sui/util-types": [
    "Class",
    "IObjectWithIndex",
    "NotFunction",
    "Nullable"
  ]
};
