///////////////////////////////////
//FILE IS AUTOGENERATED. DON'T EDIT
///////////////////////////////////
export const importsByNewPackage = {
  "@sui/ui-observable": [
    "Observable",
    "IObservableBinderProps",
    "ObservableBinder",
    "ObservableLocalStorageValue",
    "ObservableHandler",
    "ObservableHandlerStub",
    "joinObservables2",
    "joinObservables3",
    "joinObservables4",
    "joinObservables5",
    "joinObservables6"
  ],
  "@sui/util-chore": [
    "DataKey",
    "normalizeDataKey",
    "concatDataKey",
    "getDataByKey",
    "DataKeyNode",
    "dataKeysToDataTree",
    "TOrCallback",
    "getTOrCall"
  ],
  "@sui/util-types": [
    "Class",
    "Nullable",
    "NotFunction",
    "IObjectWithIndex"
  ]
};
