export {ThemeConfig} from "antd5/es/config-provider/context";
export {ArgsProps} from "antd5/es/notification/interface";
export {default as ruRU} from "antd5/locale/ru_RU";
export {CustomIconComponentProps} from "@ant-design/icons/lib/components/Icon";
export type CardType = "inner";
export type {ButtonType, ButtonGroupProps} from "antd5/lib/button";
export type {SelectValue} from "antd5/lib/select";
export type {CheckboxChangeEvent} from "antd5/lib/checkbox";
export type {SizeType} from "antd5/lib/config-provider/SizeContext";
export type {TextAreaProps} from "antd5/lib/input/TextArea";
export type {FormListProps} from "antd5/lib/form/FormList";
export type {NamePath} from "antd5/lib/form/interface";
export type {ButtonHTMLType} from "antd5/lib/button/buttonHelpers";
export type {ColumnType} from "antd5/lib/table";
export type {RcFile} from "antd5/lib/upload/interface";
export type {PresetColorType} from "antd5/lib/_util/colors";
