version: '2.1'
services:
  verdaccio:
    build: .
    container_name: verdaccio
    volumes:
       - verdaccio:/verdaccio
    - networks:
       - traefik_proxy
    labels:
      - "traefik.frontend.rule=Host:verdaccio.smp.sm-soft.ru"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external: true

volumes:
  verdaccio:
    driver: local